// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCyUOKQm7cfiVcyza3v7ewlZTrxOLGTKo',
    appId: '1:440479016164:android:27828e33e16bbf9bf6b8f1',
    messagingSenderId: '440479016164',
    projectId: 'flutter-ecommerce-app-980e0',
    storageBucket: 'flutter-ecommerce-app-980e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnxPjQW__TRBFjnenE49hGP5WeyuP0IY',
    appId: '1:440479016164:ios:8578fb3bb8b9a6cef6b8f1',
    messagingSenderId: '440479016164',
    projectId: 'flutter-ecommerce-app-980e0',
    storageBucket: 'flutter-ecommerce-app-980e0.appspot.com',
    androidClientId: '440479016164-lkq5986k2b2ma0tbri6p33jf25jt26lv.apps.googleusercontent.com',
    iosClientId: '440479016164-qt2su4hsfd253qiiagtbf4vfieqb5mcb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );
}
